### ISSUE TITLE
Rename to framer-example.framer?

### ISSUE THREAD

**Issue by tmcw** [mayagao/framer-example#1]
I think Framer needs files to end with `.framer` in order to open them, so a checkout of this repo currently can't be opened easily by the tool. We could rename the repo to framer-example.framer, or move the contents into a similarly-named dir.

**Comment by mayagao** [comment]
close with https://github.com/mayagao/framer-example/commit/bd6524ed06a196eb64e37ae5010cbf185b8d7e13
